<a href="https://colab.research.google.com/github/saadalshahranijob-glitch/Level1Projects/blob/main/project_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1: Import Libraries

In [ ]:
# Nawaf
import pandas as pd

# Step 2: Load Data

In [ ]:
# Mohammed
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yashdev01/spotify-tracks-dataset")

print("Path to dataset files:", path)
df = pd.read_csv(path + "/spotify-tracks-dataset.csv")

Using Colab cache for faster access to the 'spotify-tracks-dataset' dataset.
Path to dataset files: /kaggle/input/spotify-tracks-dataset

In [ ]:
df

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Unnamed: 0.1        0
Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

Unnamed: 0.1        0
Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

# Step 3: Mathematical Focus

AX = λX:

In [ ]:
# Mohammed
import sympy as sp

a, b, c, d = sp.symbols('a b c d')
A = sp.Matrix([[a, b],
               [c, d]])
λ = sp.symbols('λ')
x1, x2 = sp.symbols('x1 x2')
X = sp.Matrix([[x1],
               [x2]])
eq = sp.Eq(A@X, λ*X)
print("AX = λX:")
sp.pprint(eq)

AX = λX:
⎡a⋅x₁ + b⋅x₂⎤   ⎡x₁⋅λ⎤
⎢           ⎥ = ⎢    ⎥
⎣c⋅x₁ + d⋅x₂⎦   ⎣x₂⋅λ⎦



```
```

Characteristic equation:

In [ ]:
# Mohammed
I = sp.eye(2)
char_eq = A - λ*I
char_eq_det = sp.det(char_eq)
print("\nCharacteristic equation:")
sp.pprint(sp.Eq(char_eq_det, 0))
print('-'*100)


#
A = sp.Matrix([[2, 1],
               [1, 2]])


λ = sp.symbols('λ')
x1, x2 = sp.symbols('x1 x2')
X = sp.Matrix([[x1],
               [x2]])


eq = sp.Eq(A*X, λ*X)
print("AX = λX:")
sp.pprint(eq)


I = sp.eye(2)             #
char_eq = A - λ*I
char_eq_det = sp.det(char_eq)
print("\nCharacteristic equation:")
sp.pprint(sp.Eq(char_eq_det, 0))


eigenvals = sp.solve(char_eq_det, λ)
print("\nEigenvalues (λ):", eigenvals)


for val in eigenvals:
    vecs = (A - val*I).nullspace()
    print(f"\nEigenvector(s) for λ = {val}:")
    sp.pprint(vecs[0])

Characteristic equation:
                         2
a⋅d - a⋅λ - b⋅c - d⋅λ + λ  = 0
----------------------------------------------------------------------------------------------------
AX = λX:
⎡2⋅x₁ + x₂⎤   ⎡x₁⋅λ⎤
⎢         ⎥ = ⎢    ⎥
⎣x₁ + 2⋅x₂⎦   ⎣x₂⋅λ⎦

Characteristic equation:
 2
λ  - 4⋅λ + 3 = 0

Eigenvalues (λ): [1, 3]

Eigenvector(s) for λ = 1:
⎡-1⎤
⎢  ⎥
⎣1 ⎦

Eigenvector(s) for λ = 3:
⎡1⎤
⎢ ⎥
⎣1⎦

Eigenvalue interpretation:

In [ ]:
# Saad

Diagonalization:

In [ ]:
# Saad

# Step 4: AI Connection

Principal Component Analysis (PCA):

In [ ]:
# Nawaf

Principal directions:

In [ ]:
# Abdulmajeed

Variance explanation:

In [ ]:
# Abdulmajeed

# Step 5: Visualization

In [ ]:
# Abdullah